### PR TITLE
adding visual studio integration recipe

### PR DESCRIPTION
**Pull request by itlackey**
Here a quick Visual Studio integration recipe I put together. Let me know if you see any changes that need to be made etc.
Thanks!

### CODE REVIEW

**Comment by stefanwalther** [comment]
Thx, I'll have a look at it, great.

**Comment by itlackey** [comment]
Cool, thanks!

I hope it's ok I added the vscode integration recipe to this request too. I can split them up if you want?

**Comment by doowb** [comment]
This looks awesome! Thanks.

**Comment by itlackey** [comment]
Just checking in, is there anything I need to do on this?

**Comment by doowb** [comment]
I haven't had a chance to test this since I don't have a windows vm or visual studio at the moment.

If @jonschlinkert or @stefanwalther agree, I think we can merge this in so it's available for others to see and use.

**Comment by itlackey** [comment]
Ahh ok, I can possibly spin up a public vm with visual studio installed if that helps. Just let me know and I will see what I can do.

**Comment by doowb** [comment]
@itlackey I don't think that's necessary.

**Comment by jonschlinkert** [comment]
@itlackey thanks for this!

**Comment by itlackey** [comment]
thank you for all of your hard work and for putting up with my newb questions in the gitter channel @doowb  ;)

**Pull request merged**
